### ISSUE TITLE
Erro ao clicar no ticket

### ISSUE THREAD

**Issue by ramonbanda7** [renissonveras/tikiri#13]
Após abrir um ticket, vou para listar onde estão todos os tickets pendentes. Ao clicar no ticket, sou redirecionado para a url ./thread/1

E não o ticket e aparece a segunte mensagem:

"Desculpe, algo esta errado"
"Estamos trabalhando para corrigir essa situação."

**Comment by renissonveras** [comment]
Você abriu o ticket como cliente ou como atendente?

**Comment by ramonbanda7** [comment]
Olá! Boa pergunta, havia feito como admin. Então na dúvida refiz a instalação como está nas instruções aqui no github. Então, fiz um com "cliente@tikiri.com.br", então logado como admin ao clicar no ticket me veio o seguinte erro:
URL:/thread/1

ERRO:
Whoops, looks like something went wrong.
1/1
FatalErrorException in Ticket_Thread.php line 136:
Call to undefined function App\Model\helpdesk\Ticket\imap_mime_header_decode()

**Comment by ramonbanda7** [comment]
Resolvido. Apenas precisei instalar a função imap do php (apt-get install php5.6-imap) . Mas fica a dica para mudança. Pois nos requisitos de instalação não vem como obrigatório e para quem acessa o sistema pela primeira vez, não imagina que essa extensão se faz necessária apenas para ler o ticket! valeu!

**Comment by renissonveras** [comment]
Muito bom... estamos a disposição!
