### ISSUE TITLE
erro 404

### ISSUE THREAD

**Issue by romulocomin** [renissonveras/tikiri#14]
Olá bom dia, tentei instalação clonado o tikiri, já de inicio erro 500, então segui o outro passo, com arquivo .sql, a página inicial carrega normalmente, porém qualque outro como login por exemplo, da erro 404, sei que é erro de configuração do apache ou .htacess, gostaria de uma dica.

**Comment by renissonveras** [comment]
Rômulo, roda o avaliador (https://github.com/renissonveras/avaliador) e verifica quais dependencias não foram satisfeitas. Pelo erro que você descreveu é provável que o mod_rewrite não esteja configurado corretamente.
