### ISSUE TITLE
Não deleta tickets

### ISSUE THREAD

**Issue by nicolasmdc** [renissonveras/tikiri#16]
Olá!
Na caixa de entrada, ao selecionar um ou vários tickets e clicar em DELETAR, após confirmar a exclusão, o sistema apresenta a mensagem:
"Os tickets foram excluídos permanentemente"
Porém eles permanecem na caixa de entrada, não vão para a lixeira.
Algo que eu possa fazer? 
Obrigado

**Comment by renissonveras** [comment]
Nicolas, está usando a última versão? Corrigimos este bug a alguns commits atrás. Aguardo teu retorno.

**Comment by nicolasmdc** [comment]
Olá.
Realmente a versão que tenho já é mais antiga, preciso atualizar tudo ou tem algum arquivo especifico? 
Obrigado pelo retorno
