### ISSUE TITLE
Recebimento de Ticket por e-mail

### ISSUE THREAD

**Issue by nicolasmdc** [renissonveras/tikiri#18]
Olá
Fiz a configuração de email, inclui uma conta de email para recebimento por IMAP, para receber tickets através do envio da mensagem para esta conta. Porém no Tikiri as mensagens não entram.
Identifiquei que os tickets só entram no sistema se eu for até a configuração desta conta de e-mail e clicar em atualizar. Existe uma configuração que preciso fazer para que o sistema receba as mensagens de e-mail de forma automática?
Obrigado

**Comment by robertoalmeida** [comment]
Olá Nicolas,
Na opção do Painel Admin > Configurações > Agenda de Tarefas 
Configure as 3 opções e coloque no cron:

* * * * * /usr/bin/php -q  /var/www/html/tikiri/code/artisan schedule:run >> /dev/null

**Comment by nicolasmdc** [comment]
Olá Roberto
Obrigado pelo retorno.
Porém tenho o sistema hospedado na Locaweb, e estive verificando no painel e os agendamentos Cron deles só se executam as 2 da manhã.. não sei o por quê..

**Comment by robertoalmeida** [comment]
É necessário o agendamento permanente no intervalo de tempo de sua escolha para as verificações tanto de mensagens de entrada como de saída.
No exemplo que enviei a verificação é a cada minuto.
Eu rodo o tikiri em uma máquina Linux de 5 dólares e funciona perfeitamente.
Essa limitação do cron em rodar somente uma vez ao dia, na minha opinião inviabiliza o uso nesta hospedagem.

**Comment by nicolasmdc** [comment]
> É necessário o agendamento permanente no intervalo de tempo de sua escolha para as verificações tanto de mensagens de entrada como de saída.
> No exemplo que enviei a verificação é a cada minuto.
> Eu rodo o tikiri em uma máquina Linux de 5 dólares e funciona perfeitamente.
> Essa limitação do cron em rodar somente uma vez ao dia, na minha opinião inviabiliza o uso nesta hospedagem.

Qual seria essa sua maquina linux? Qual serviço??

**Comment by robertoalmeida** [comment]
https://www.digitalocean.com/?refcode=986b5752a80f

**Comment by pvitorribeiro** [comment]
@nicolasmdc  sobre esse problema com a Locaweb, como você tratou ?  O estranho é que mesmo fazendo a configuração do Cron ele não foi executado na madrugada.

**Comment by nicolasmdc** [comment]
@pvitorribeiro não consegui resolver com a hospedagem web deles, tentei no suporte e me informaram que só mesmo através do agendador disponível no painel administrativo, e sim, pra mim também não funcionou, na madrugada ele executa mas não roda o comando, (descobri isso pelos logs no ftp da locaweb). A solução deles é hospedar em um VPS. Acho que é justamente pra isso que o CRON deles tem essa limitação ¬¬
