### ISSUE TITLE
Troca de e-mail atendente

### ISSUE THREAD

**Issue by ghost** [renissonveras/tikiri#19]
Bom dia,

Ao tentar trocar o e-mail de um atendente ele me retornar o erro.

O campo já está preenchido.

**Comment by renissonveras** [comment]
Opa Felipe, esse erro ocorre quando este email já está sendo utilizado por outro usuário. Vou deixar o ticket aberto pra melhorar a mensagem. Abraço

**Comment by ghost** [comment]
Opa legal,

 

Já deu certo. Alterei o outro estava em user de teste e deu certo.

 

De: Renisson Veras [mailto:notifications@github.com] 
Enviada em: terça-feira, 21 de maio de 2019 15:22
Para: renissonveras/tikiri <tikiri@noreply.github.com>
Cc: Felipe Baum <felipe.baum@sislogica.com.br>; Author <author@noreply.github.com>
Assunto: Re: [renissonveras/tikiri] Troca de e-mail atendente (#19)

 

Opa Felipe, esse erro ocorre quando este email já está sendo utilizado por outro usuário. Vou deixar o ticket aberto pra melhorar a mensagem. Abraço
