### ISSUE TITLE
Não consigo instalar

### ISSUE THREAD

**Issue by azeved-tm** [renissonveras/tikiri#20]

**Comment by nicolasmdc** [comment]
Qual o problema?

**Comment by renissonveras** [comment]
Pode descrever melhor o problema?

**Comment by azeved-tm** [comment]
tentei instalar a partir do manual.
Mas não consigo compreender, o passo a passo para a instalação.
"meu forte não é programação, tenho uma assistência técnica é desejo colocar esse sistema em meu servidor web".

**Comment by robertoalmeida** [comment]
Qual linux você tá utilizando? Vou publicar um passo a passo da instalação em no Centos Linux 7.

**Comment by nicolasmdc** [comment]
Bom, vou descrever como eu fiz, quem sabe fica claro pra você:
- Tenho um plano de hospedagem de sites, então criei um subdomínio no meu plano (geralmente os serviços de hospedagem possibilitam isso)
- Baixei os arquivos aqui pelo GIT em formato Zip e fiz o upload descompactando eles para a pasta do meu serviço de hospedagem onde está apontado o subdomínio.
- Criei o banco de dados no mysql (outro serviço as hospedagens fornecem)
- Conforme o tutorial de instalação, editei o arquivo .env com os dados do banco (bd, usuario e senha)
- E para editar as permissões das pastas, o serviço de hospedagem tem algumas funções para isso no seu gerenciador de arquivos.
- Para acessar a ferramenta, eu apenas digito no navegador o endereço do subdomínio que criei.
Caso você utilize algum serviço de hospedagem, pode variar os passos, mas a essência é a mesma.

**Comment by robertoalmeida** [comment]
Tenta rodar o avaliador que testa seu ambiente.

https://github.com/renissonveras/avaliador
