### ISSUE TITLE
Erro ao efetuar abertura de ticket através de usuário logado.

### ISSUE THREAD

**Issue by nicolasmdc** [renissonveras/tikiri#24]
Olá
Ao preencher as informações do ticket e clicar em Enviar, o mesmo demora muito para executar, até 1 minuto de espera, depois ele exibe uma mensagem de Ticket Criado com Sucesso, mas logo abaixo uma mensagem de Alerta. Conforme imagem em anexo.

![Screenshot_1](https://user-images.githubusercontent.com/48808596/59718215-0bf07f80-91f0-11e9-9a4b-bb3a1923350c.jpg)

**Comment by jfaustinoni** [comment]
Olá,

Também estou com o mesmo problema.

**Comment by renissonveras** [comment]
Fiz uns testes, é um bug de versão... aviso quando corrigir

**Comment by renissonveras** [comment]
Pessoal, bug corrigdo na atualização de hoje
