### ISSUE TITLE
Erro ao navegar, não abre nenhuma página!

### ISSUE THREAD

**Issue by flavioodias** [renissonveras/tikiri#25]
Segui os passos instalei em servidor linux e windows para testes, parei no mesmo erro.
Arquivo não encontrado, acredito que o DOWNLOAD não esta completo!

Rodei o Verificador e esta tudo OK!

Aguardo, e muito obrigado.

**Comment by renissonveras** [comment]
Possíveis erros na instalação, usuário orientado via whats. Fechando...
