### ISSUE TITLE
Extensão Mcrypt

### ISSUE THREAD

**Issue by joaresabreu** [renissonveras/tikiri#26]
Bom dia,

Sei que o Tikiri é homologado para o php 5.6, e como isso tenha enfrentado dificuldades e instalar a extensão "mcrypt" já que a mesma caiu em desuso. Poderiam me ajudar com este caso, pois já pesquisei mas não consegui instalar este recurso no php que estou usando na versão 7.2 e o ambiente é windows com o Xampp.

**Comment by renissonveras** [comment]
Melhor opção no seu caso, imagino é instalar uma máquina virtual pra rodar o Tikiri no windows
