### ISSUE TITLE
Logo exibindo nome de outra empresa

### ISSUE THREAD

**Issue by nicolasmdc** [renissonveras/tikiri#4]
Olá
Ao posicionar o mouse sobre o logo do Tikiri, na pagina inicial ele exibe um balão com o nome de outra empresa (InforRR Soluções em Tecnologia)

**Comment by renissonveras** [comment]
Obrigado @nicolasmdc , erro corrigido no commit de hoje.

**Comment by renissonveras** [comment]
Se for do seu interesse alterar a mensagem é só editar o arquivo  code/resources/views/themes/default1/client/layout/client.blade.php

**Comment by ghost** [comment]
Aqui deu certo.
