### ISSUE TITLE
Erro 500 ao editar ticket

### ISSUE THREAD

**Issue by ghost** [renissonveras/tikiri#5]
Bom dia, Estou com erro 500 ao tentar trocar tópico de ajuda.

**Comment by ghost** [comment]
Qualquer item que tento alterar apresenta erro 500, não é somente no topico de ajuda.

**Comment by renissonveras** [comment]
Pode enviar o erro que aparece no log? code/storage/log/laravel....log

**Comment by renissonveras** [comment]
Resolvido no commit dd53f02
