### ISSUE TITLE
ao enviar um ticket sem realizar cadastro

### ISSUE THREAD

**Issue by ghost** [renissonveras/tikiri#9]
Erro ao enviar ticket.

ErrorException {#1512 ▼
  #message: "Trying to get property of non-object"
  #code: 0
  #file: "/var/www/html/suporte/code/app/Plugins/Gamification/routes.php"
  #line: 41
  #severity: E_NOTICE
  -trace: {▶}
}

**Comment by ghost** [comment]
Neste caso percebi que o ticket é aberto porem não apresenta a pagina de aberto com sucesso e vai para o erro mencionado.

**Comment by renissonveras** [comment]
Corrigindo

**Comment by renissonveras** [comment]
Felipe, no commit de hoje corrigi essa falha. É só atualizar.
